### PR TITLE
Adding support for dapr version v1.11.0. 

### PR DESCRIPTION
**Pull request by arturotrenard**
…mented details in the state component.

# Description
In the latest versions of Dapr the definition of the pubsub interface changed. And it is necessary to support the creation of new pluggable components of type pubsub to update the version of the dapr package used.

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] Code compiles correctly
- [ ] Created/updated tests
- [ ] Unit tests passing

### CODE REVIEW

**Review by artursouza — COMMENTED** [review]
Overall, looks good. Just needs to finish the code that was commented out.

**Comment by philliphoff** [comment]
@artursouza Looks ok to me, pending successful tests.  We should probably enforce sign off's on the repo prior to committing.  (I don't have permissions to switch that on.)

**Comment by arturotrenard** [comment]
@artursouza then based on what we talked about in discord I am pending the merge of the PR since there is nothing pending. Thank you for everything and I'm at your service for anything.

**Comment by arturotrenard** [comment]
The workflow file that was also missing was updated. .github/workflows/ci.yaml for go 1.20

**Comment by artursouza** [comment]
> 

done

**Review by artursouza — APPROVED** [review]

**Pull request merged**
